language: python
sudo: required
dist: xenial
before_install:
- chmod +x .build/.travis/*.sh
matrix:
  include:
  - env: IMG="ubuntu1604" BUILD_TARGET="pex"
    python:
    - 3.6
    install:
    - .build/.travis/install-ubuntu.sh
    script:
    - .build/.travis/build-py36.sh
    - .build/.travis/release.sh
    - python setup.py test
  - env: IMG="ubuntu1604" BUILD_TARGET="standalone"
    python:
    - 3.6
    install:
    - .build/.travis/install-ubuntu.sh
    script:
    - .build/.travis/build-py36.sh
    - .build/.travis/release.sh
    - python setup.py test
  - env: IMG="ubuntu1604" BUILD_TARGET="pex"
    python:
    - 2.7
    install:
    - .build/.travis/install-ubuntu.sh
    script:
    - .build/.travis/build-py27.sh
    - .build/.travis/release.sh
    - python setup.py test
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c"
    services:
    - docker
    # for logging purposes
    python:
    - 3.6
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e TRAVIS_TAG="${TRAVIS_TAG}" ${OS} tail -f /dev/null
    - docker ps
    install:
    - $SH .build/.travis/install-centos.sh
    script:
    - $SH .build/.travis/build-py36-centos.sh
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c"
    services:
    - docker
    # for logging purposes
    python:
    - 2.7
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e TRAVIS_TAG="${TRAVIS_TAG}" ${OS} tail -f /dev/null
    - docker ps
    install:
    - $SH .build/.travis/install-centos.sh
    script:
    - $SH .build/.travis/build-py27.sh
    - $SH .build/.travis/release.sh
    - $SH "python setup.py test"

deploy:
  provider: releases
  api_key:
    secure: p6QQnxJoqILH9jf1yo9HewkV7WxHqEhMac4PRmBjapxg26oi+52TZrpmDClvpO8vYeZ/c1Iagh1g5DHb9nZzb5VihV0wmLVeYm/o/fxuXpx5FyhlzNWOgcRsXDHa3lx3lOasYlSCtj3VCQymnGhnAJDYF3LN8gu9paykEoH0soYALFrFkvgwkzEaS9AXuLtVyiV0ic1H9pF93kvBijO7OIebx7EDObCTqfAQDHOoOM5Lo6A61n9vbuxKGC/Tq6x+LXHM32s4/xodO2Ctcqq5H0ebghR/Jb8ovajpIRup6Tp+WURMLDd6jhy7SOhbF9zofsaejhlmg4HGZacJNME5YRY8xHyVVznygDte2EBcFOftI/Et9wfgVuDe1+ceGWM0ah2sttBGoFWLRgWUUVQDKbYJJoTdPmsaRriKJEuqoK+YGI7y2Z+ZIibAZ9X8vQ3BVV9dYr9zxoaahducsb+8zln/AISKOBhESzLEKtZTPA3qv16N08qLGY6v5g4BJHKA3T+jo8NNNxSet/5kOiL7z9ciSJOrNela7rGrttLeTvWCcWRWSd7UNr9fFetuncDuUZf50j1ndVaG41UwTSbZxVGO+N5yG2GKGRujFP1npEc9jKcWzSiOl+Aw9Y3nGVhLffOGkTwAcoGhr4xQbs1yYNuL2jf84eA2ouBgEyxyQJE=
  file_glob: true
  file: release/*.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: adobe-apiplatform/user-sync.py
    all_branches: true
