dashboard:
  # specifies the configurations for the Adobe Enterprise Dashboards.  
  # By default, it would look for dashboard-owning-config.yml and
  # dashboard-trustee-*-config.yml in the configuration path,
  # with the yml's identifying the owning organization and trustee organizations
  # respectively.
  #  
  # You can also specify the configurations under this section too,
  # with keys owning and trustees.
  #
  # Examples:
  # owning: example.dashboard-config.yml
  # trustees:
  #   org1: example.dashboard-config.yml    

  # specifies the filename for the owning org configuration.  Default is:
  # owning_config_filename: "dashboard-owning-config.yml"
  
  # specifies the filename format for the trustee org configurations.  
  # a filename that matches the format will have the organization name extracted 
  # from the filename. Default is:
  # trustee_config_filename_format: "dashboard-trustee-{organization_name}-config.yml"

directory:
  connectors:
    # specifies the configurations for the difference directory connectors
    # The format is name : value, where value can be:
    # a dictionary for the actual configuration, or 
    # a string for the file containing the configuration, or
    # a list containing a mixture of dictionaries and strings
    #
    # examples:   
    # ldap: example.connector-ldap.yml
    # ldap: 
    #   - host: LDAP_host_URL_goes_here
    #     base_dn: base_DN_goes_here
    #   - connector-ldap-credentials.yml
 
  groups:
    # specifies the list of group mappings, with each group mapping consisting
    # of a dictionary with keys: directory_group and dashboard_groups.    
    # directory_group: string identifying the group in the directory
    # dashboard_groups: a list of strings identifying the dashboard groups.
    #
    # a group in dashboard_groups can be qualified with, the first part being
    # the trustee organization name.
    # e.g. org1::Default Acrobat Pro DC configuration
    #
    # examples:
    # - directory_group: AdobeCC-All #Group CN
    #   dashboard_groups:
    #     - All Apps
    # - directory_group: AdobeCC-Photoshop
    #   dashboard_groups:
    #     - Photoshop Users
    # - directory_group: acrobat
    #   dashboard_groups:
    #     - org1::Default Acrobat Pro DC configuration

  # specifies the default identity type of the dashboard user to create,
  # when the identity type of a user is missing.  
  # valid values are: enterpriseID, federatedID
  # 
  # Default is:
  # user_identity_type: enterpriseID

logging:
  # specifies whether you wish to generate a log file
  # 'True' or 'False'
  log_to_file: True
  # output path for logs
  file_log_directory: logs
  # File Logging Level: Can be "debug", "info", "warning", "error", or "critical".  
  # This is in ascending order, meaning "debug" < "critical".
  file_log_level: debug
  # Console Logging Level: Can be "debug", "info", "warning", "error", or "critical".  
  # This is in ascending order, meaning "debug" < "critical".  Default is:
  # console_log_level: debug